python cifar10-multi-gpu-horovod.py --batch-size 256 \
--epochs 30 \
--learning-rate 0.01 \
--momentum 0.9 \
--optimizer sgd \
--weight-decay 0.0002 \
--gpu-count 0 \
--train ~/SageMaker/cifar10-dataset/train \
--eval ~/SageMaker/cifar10-dataset/eval \
--validation ~/SageMaker/cifar10-dataset/validation \
--model_dir '/opt/training' \
--output_data_dir ~/SageMaker/local_files \
--tensorboard_dir ~/SageMaker/local_files
